SCIInstitute/SCIRun

- src/Interface/Modules/Render/ES/systems/RenderBasicSys.cc
@dcwhite Hee is a fix for the workaround you made
here:https://github.com/SCIInstitute/SCIRun/commit/e99813a82ecb2b73890e8976b13be00e346d8dbb#commitcomment-9193430
> Face transparency flip

- src/Interface/Application/SCIRunMainWindow.cc
- src/Interface/Modules/Base/ModuleDialogGeneric.cc
- src/Interface/Modules/Base/ModuleDialogGeneric.h
- src/Interface/Modules/BrainStimulator/ElectrodeCoilSetupDialog.cc
- src/Interface/Modules/BrainStimulator/GenerateROIStatisticsDialog.cc
- src/Interface/Modules/BrainStimulator/SetConductivitiesToTetMeshDialog.cc
- src/Interface/Modules/BrainStimulator/SetupRHSforTDCSandTMSDialog.cc
- src/Interface/Modules/Forward/BuildBEMatrixDialog.cc
- src/Interface/Modules/Visualization/ShowFieldDialog.cc
Any color changes will be easy from here. Let me know if you have any suggestions/fixes.
> Ben style sheet

- src/Interface/Modules/Render/ES/SRInterface.cc
- src/Interface/Modules/Render/ES/systems/RenderTransBasicSys.cc
- src/Interface/Modules/Render/ES/systems/RenderTransColorMapSys.cc
- src/Interface/Modules/Render/ViewSceneControls.ui
- src/Interface/Modules/Render/ViewSceneControlsDock.cc
This is so that we can use the intermittent rendering in the demos for better performance.
> Intermittent trans

- src/Core/Algorithms/BrainStimulator/SetupRHSforTDCSandTMSAlgorithm.cc
- src/Core/Algorithms/BrainStimulator/SetupRHSforTDCSandTMSAlgorithm.h
- src/Interface/Modules/BrainStimulator/SetupRHSforTDCSandTMSDialog.cc
- src/Interface/Modules/BrainStimulator/SetupRHSforTDCSandTMSDialog.ui
- src/Modules/BrainStimulator/SetupRHSforTDCSandTMS.cc
I added a new checkbox. 
One GUI problem:
It seems that the checkbox status (if its checked or not) gets saved in the network file
but does not reflect the GUI after reloading.
@dcwhite Could you have a look at this.
Thanks!
> update on SetupTDCS; (1) contact surface extraction (2) point electrodes

- src/ExampleNets/FwdInvToolkit/activation-based-fem.srn5
- src/ExampleNets/FwdInvToolkit/forward_problem.srn5
- src/ExampleNets/FwdInvToolkit/tikhonov-inverse.srn5
- src/ExampleNets/FwdInvToolkit/torso-tank-bem.srn5
Added in the RescaleColorMap module to the FwdInvToolkit examples.
> Added the RescaleColorMap modules to FwdInvToolkit example networks.

- src/ExampleNets/IBBM2015/DipoleSourceExample.srn5
- src/ExampleNets/IBBM2015/cube_simulation.srn5
- src/ExampleNets/IBBM2015/defib_FEM_eval.srn5
- src/ExampleNets/IBBM2015/view_fibers.srn5
> add some new modules to existing IBBM networks

- src/ExampleNets/IBBM2015/Display_PhiE_data.srn5
- src/ExampleNets/IBBM2015/Isosurfacing_Cube.srn5
- src/ExampleNets/IBBM2015/Isosurfacing_Hip.srn5
- src/ExampleNets/IBBM2015/Registration_Network.srn5
- src/ExampleNets/IBBM2015/data_visualization_NEEDS_MODULES.srn5
- src/ExampleNets/IBBM2015/greensite.srn5
- src/ExampleNets/IBBM2015/streamline.srn5
- src/ExampleNets/IBBM2015/wbp.srn5
most of the new networks work with the data now.  Some are still missing modules or features.
> preping the IBBM networks with data for testing

- src/ExampleNets/IBBM2015/BrainStimulator_TDCS.srn5
- src/ExampleNets/IBBM2015/BrainStimulator_TDCS_complex.srn5
- src/ExampleNets/IBBM2015/BrainStimulator_TMS.srn5
I resaved the network files with the latest master build.
> final check of brainstimulator ibbm examples

- src/Core/Algorithms/BrainStimulator/ElectrodeCoilSetupAlgorithm.cc
Small update. Coming more soon for this module.
> bug fix and speed-up.

- src/Core/Algorithms/DataIO/Tests/ReadMatrixTests.cc
- src/Core/Application/Version.cc
- src/Core/Datatypes/Legacy/Field/TriSurfMesh.h
- src/Core/Utils/Legacy/Environment.cc
- src/Core/Utils/Legacy/Environment.h
- src/Core/Utils/Legacy/Environment_Defaults.cc
- src/Core/Utils/Legacy/FileUtils.cc
- src/ExampleNets/regression/EnvironmentStringBundle.srn5
- src/Interface/Modules/Bundle/CMakeLists.txt
- src/Interface/Modules/Bundle/GetStringsFromBundleDialog.cc
- src/Interface/Modules/Bundle/GetStringsFromBundleDialog.h
- src/Interface/Modules/Bundle/GetStringsFromBundleDialog.ui
- src/Main/CMakeLists.txt
- src/Main/scirunMain.cc
- src/Modules/Factory/Config/GetStringsFromBundle.module
- src/Modules/Factory/Config/InsertEnvironmentIntoBundle.module
- src/Modules/Legacy/Bundle/CMakeLists.txt
- src/Modules/Legacy/Bundle/GetStringsFromBundle.cc
- src/Modules/Legacy/Bundle/GetStringsFromBundle.h
- src/Modules/Legacy/Bundle/InsertEnvironmentIntoBundle.cc
- src/Modules/Legacy/Bundle/InsertEnvironmentIntoBundle.h
- src/Modules/Legacy/Bundle/ReportBundleInfo.cc
This is a branch for two modules: InsertEnvironmentIntoBundle and GetStringsFromBundle.  GetStringsFromBundle is completely ported and is working properly.  InsertEnvironmentIntoBundle is not working yet.  The guts of the module have been commented out because it is dependent on environment.cc which has not been converted.  This is a bit complicated for me to convert.
> Environment bundle

- src/Core/IEPlugin/CMakeLists.txt
- src/Core/IEPlugin/IEPluginInit.cc
- src/Core/IEPlugin/IgbFileToMatrix_Plugin.cc
- src/Documentation/Manuals/BasicTutorial/BasicTutorial.tex
Add to remove a section from the Basic Tutorial that will be implemented elsewhere.
> Updates to the Basic Tutorial: Removing User Interface section

- src/Core/IEPlugin/IEPluginInit.cc
- src/Core/IEPlugin/IgbFileToMatrix_Plugin.cc
Currently, the code does not properly handle the data that should be outputted.
> Updates to the IGB importer: code included 

- src/Core/IEPlugin/IgbFileToMatrix_Plugin.cc
Added some code to check for length allowing for incomplete files.
> Changes to IGB importer to allow for imcomplete files

- src/Interface/Modules/Base/ModuleDialogGeneric.cc
- src/Interface/Modules/Base/ModuleDialogGeneric.h
- src/Interface/Modules/Fields/ExtractSimpleIsosurfaceDialog.cc
- src/Interface/Modules/Fields/ExtractSimpleIsosurfaceDialog.h
Made a new widget manager for this.
> Closes #1495

- src/Core/Command/Command.h
- src/Core/ConsoleApplication/ConsoleCommandFactory.cc
- src/Core/ConsoleApplication/ConsoleCommands.h
- src/Dataflow/Engine/Controller/PythonImpl.cc
- src/Dataflow/Network/Connection.cc
- src/Dataflow/Network/Connection.h
- src/Dataflow/Network/DataflowInterfaces.h
- src/Dataflow/Network/Port.cc
- src/Dataflow/Network/Port.h
- src/Dataflow/Network/PortInterface.h
- src/Dataflow/Network/SimpleSourceSink.cc
- src/Dataflow/Network/SimpleSourceSink.h
- src/Dataflow/Network/Tests/MockPorts.h
- src/Interface/Application/GuiCommandFactory.cc
- src/Interface/Application/GuiCommands.cc
- src/Interface/Application/GuiCommands.h
- src/Interface/Application/ModuleWidget.cc
- src/Interface/Application/ModuleWidget.h
- src/Interface/Application/NetworkEditor.cc
- src/Interface/Application/NetworkEditor.h
- src/Interface/Application/Port.cc
- src/Interface/Application/Port.h
- src/Testing/ModuleTestBase/ModuleTestBase.cc
Helps with VS crashes in python execution contexts. See #1490
> Python vs restrictions

- src/Core/Algorithms/Legacy/Fields/MeshDerivatives/GetFieldBoundaryAlgo.cc
- src/Core/Algorithms/Legacy/Fields/MeshDerivatives/GetFieldBoundaryAlgo.h
- src/Core/Datatypes/Legacy/Field/HexVolMesh.h
- src/Core/Datatypes/Legacy/Field/PrismVolMesh.h
- src/Core/Datatypes/Legacy/Field/QuadSurfMesh.h
- src/Core/Datatypes/Legacy/Field/TetVolMesh.h
- src/Core/Datatypes/Legacy/Field/TriSurfMesh.h
- src/Dataflow/Network/Module.cc
- src/ExampleNets/regression/embb2.srn5
- src/Interface/Application/MainWindowCollaborators.h
- src/Interface/Application/SCIRunMainWindow.cc
- src/Interface/Application/Settings.cc
- src/Interface/Modules/Base/ModuleDialogGeneric.cc
- src/Interface/Modules/Fields/EditMeshBoundingBox.ui
- src/Interface/Modules/Fields/EditMeshBoundingBoxDialog.cc
- src/Interface/Modules/Fields/EditMeshBoundingBoxDialog.h
- src/Interface/Modules/Fields/GenerateSinglePointProbeFromFieldDialog.cc
- src/Interface/Modules/Math/GetMatrixSliceDialog.cc
- src/Interface/Modules/Visualization/ShowColorMapDialog.cc
- src/Interface/Modules/Visualization/ShowFieldDialog.cc
- src/Interface/Modules/Visualization/ShowFieldGlyphsDialog.cc
- src/Modules/Fields/BoxWidgetTypes.h
- src/Modules/Fields/EditMeshBoundingBox.cc
- src/Modules/Fields/EditMeshBoundingBox.h
Headless time logging, faster GetFieldBoundary, refactoring. Does not actually add much to toolkit download menu, I pushed that one for later.
> EMBB reset and more

- src/Core/Application/Preferences/CMakeLists.txt
- src/Core/Application/Preferences/Preferences.cc
- src/Core/Python/PythonInterpreter.cc
- src/Core/Python/PythonInterpreter.h
- src/Core/Utils/Legacy/CMakeLists.txt
- src/Modules/Python/InterfaceWithPython.cc
@jessdtate @gduffley Please test your issues off of this PR branch.
> Two small python improvements

- src/Core/Algorithms/Base/AlgorithmBase.cc
- src/Core/Algorithms/Base/Tests/AlgorithmBaseTests.cc
- src/Core/Application/Preferences/Preferences.cc
- src/Core/Application/Preferences/Preferences.h
Fixes over-replacing of SCIRUNDATADIR
> Closes #1568

- src/Interface/Application/ModuleProxyWidget.cc
- src/Interface/Application/ModuleProxyWidget.h
- src/Interface/Application/ModuleWidget.cc
- src/Interface/Application/ModuleWidget.h
- src/Interface/Modules/Base/CMakeLists.txt
- src/Interface/Modules/Base/ModuleButtonBar.cc
- src/Interface/Modules/Base/ModuleButtonBar.h
- src/Interface/Modules/Base/ModuleButtonBar.ui
- src/Interface/Modules/Base/ModuleDialogGeneric.cc
- src/Interface/Modules/Base/ModuleDialogGeneric.h
- src/Interface/Modules/BrainStimulator/ElectrodeCoilSetupDialog.cc
- src/Interface/Modules/BrainStimulator/ElectrodeCoilSetupDialog.ui
Nifty button bar across top of every module UI. Let me know if there are layout issues on other platforms (tested on 10.9).
> Module ui buttons

- src/Modules/Math/ConvertRealToComplexMatrix.cc
- src/Modules/Math/ConvertRealToComplexMatrix.h
- src/Modules/Math/Tests/ConvertRealToComplexMatrixTests.cc
Also sparse module input works now.
> ConvertRealToComplexMatrix_Sparse_matrix_module_input_extension

- src/Modules/Math/ConvertRealToComplexMatrix.cc
- src/Modules/Math/Tests/ConvertRealToComplexMatrixTests.cc
This implementation uses Eigen operators. It can construct a giant (Moritz-scale) sparse complex matrix; the previous implementation took forever/ran out of memory.
> Better complex matrix construction implementation

- src/Core/Algorithms/Math/SolveLinearSystemWithEigen.cc
- src/Core/Algorithms/Math/SolveLinearSystemWithEigen.h
- src/Core/Algorithms/Math/Tests/SolveLinearSystemWithEigenTests.cc
- src/ExampleNets/regression/solveComplexLinearSystem.srn5
- src/Interface/Modules/Math/CMakeLists.txt
- src/Interface/Modules/Math/SolveComplexLinearSystem.ui
- src/Interface/Modules/Math/SolveComplexLinearSystemDialog.cc
- src/Interface/Modules/Math/SolveComplexLinearSystemDialog.h
- src/Modules/Factory/Config/SolveComplexLinearSystem.module
- src/Modules/Math/ConvertComplexToRealMatrix.cc
- src/Modules/Math/SolveComplexLinearSystem.cc
- src/Modules/Math/SolveComplexLinearSystem.h
Only two solvers are available, need to upgrade Eigen to get Least Squares CG.
> Fixes and UI for Complex solver

- src/ExampleNets/regression/buildFE_1e5_viz.srn5
- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewScene.h
- src/Main/CMakeLists.txt
- src/Modules/Render/ViewScene.cc
- src/Modules/Render/ViewScene.h
> Save VS visibility state

- src/Core/Datatypes/Color.h
- src/Dataflow/Network/Module.cc
- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewScene.h
- src/Modules/Visualization/ShowColorMapModule.cc
- src/Modules/Visualization/ShowString.cc
- src/Modules/Visualization/ShowString.h
- src/Modules/Visualization/TextBuilder.cc
- src/Modules/Visualization/TextBuilder.h
Improved ShowString position logic to avoid text disappearing.
> Showstring positioning

- src/ExampleNets/regression/probeMovesWithSliceSnappingToNode.srn5
- src/Interface/Modules/Fields/GetSliceFromStructuredFieldByIndices.ui
- src/Interface/Modules/Fields/GetSliceFromStructuredFieldByIndicesDialog.cc
- src/Interface/Modules/Fields/GetSliceFromStructuredFieldByIndicesDialog.h
- src/Modules/Legacy/Fields/GetSliceFromStructuredFieldByIndices.cc
- src/Modules/Legacy/Fields/GetSliceFromStructuredFieldByIndices.h
All widgets in GSFSFBI trigger execution now.
> Closes #1642

- src/Interface/Modules/Math/BooleanCompareDialog.cc
- src/Modules/Math/BooleanCompare.h
some spelling fixes and link to new web docs
> Conditional

- src/Interface/Application/ModuleWidget.cc
- src/Interface/Application/NetworkEditor.cc
- src/Interface/Application/SCIRunMainWindow.cc
- src/Interface/Modules/Base/ModuleDialogGeneric.h
- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewScene.h
> Gui hidpi improvements and updated toolkit links

- src/Core/Application/Preferences/Preferences.cc
- src/Core/Application/Preferences/Preferences.h
- src/Core/Datatypes/Geometry.h
- src/Dataflow/Network/Module.cc
- src/Interface/Application/NetworkEditor.cc
- src/Interface/Application/NetworkEditor.h
- src/Interface/Application/Preferences.ui
- src/Interface/Application/PreferencesWindow.cc
- src/Interface/Application/PreferencesWindow.h
- src/Interface/Application/SCIRunMainWindow.cc
- src/Interface/Application/Settings.cc
- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewSceneControlsDock.cc
- src/Modules/Visualization/ShowColorMapModule.cc
- src/Modules/Visualization/ShowField.cc
Fixes for high-dpi windows laptops, and showfield naming difficulties
> Ibbm fixes

- src/Core/Algorithms/Legacy/Inverse/SolveInverseProblemWithStandardTikhonovImpl.h
- src/Core/Algorithms/Legacy/Inverse/TikhonovAlgoAbstractBase.cc
- src/Core/Algorithms/Legacy/Inverse/TikhonovAlgoAbstractBase.h
> Memory leaks

- src/Core/Math/CMakeLists.txt
- src/Core/Math/Histogram.cc
- src/Core/Math/Histogram.h
- src/ExampleNets/regression/histogramExample.srn5
- src/Externals/spire/entity-system/GenericSystem.hpp
- src/Interface/Modules/Base/CMakeLists.txt
- src/Interface/Modules/Base/CustomWidgets/QtHistogramGraph.cc
- src/Interface/Modules/Base/CustomWidgets/QtHistogramGraph.h
- src/Interface/Modules/Base/CustomWidgets/QtHistogramWidget.cc
- src/Interface/Modules/Base/CustomWidgets/QtHistogramWidget.h
- src/Interface/Modules/Base/CustomWidgets/QtHistogramWidget.ui
- src/Interface/Modules/Math/CMakeLists.txt
- src/Interface/Modules/Math/DisplayHistogram.ui
- src/Interface/Modules/Math/DisplayHistogramDialog.cc
- src/Interface/Modules/Math/DisplayHistogramDialog.h
- src/Modules/Factory/Config/DisplayHistogram.module
- src/Modules/Math/CMakeLists.txt
- src/Modules/Math/DisplayHistogram.cc
- src/Modules/Math/DisplayHistogram.h
I added a new basic module, with an example network. Check it out and see how it looks in SCIRun.
> Histogram code from Seg3d

- src/Core/Algorithms/Legacy/Fields/MeshDerivatives/ExtractSimpleIsosurfaceAlgo.cc
- src/Interface/Modules/Fields/ExtractSimpleIsosurface.ui
- src/Modules/Legacy/Fields/ExtractSimpleIsosurface.cc
- src/Modules/Legacy/Fields/ExtractSimpleIsosurface.h
- src/Modules/Visualization/RescaleColorMap.cc
TODO
In the new file, add your pull request template. This could include:
A reference to a related issue in your repository.
A description of the changes proposed in the pull request.
@mentions of the person or team responsible for reviewing proposed changes.
> added port to extractisosurface.  fix in rescale colormap

- src/Core/IEPlugin/CARPMesh_Plugin.cc
Corrected the if-else loop in the CARPMesh exporter. TODO: check the exporting of surface files using the exporter.
> Fix for CarpMesh exporter in WriteField module

- .travis.yml
Builds actually complete now, well faster than the time threshold.
> Switch to ninja for OSX travis builds

- src/Modules/Visualization/Tests/CMakeLists.txt
- src/Modules/Visualization/Tests/OsprayFieldRenderTests.cc
This is a quick change for @xuanhuang1 to get the unit test working that we were looking at today. @jessdtate, please approve asap.
> Enable original ospray unit test

- src/Interface/Modules/Render/ES/SRInterface.cc
- src/Interface/Modules/Render/ES/shaders/ColorMapLegend.vs
- src/Interface/Modules/Render/ES/shaders/ColorMapLegendText.vs
- src/Interface/Modules/Render/ES/shaders/HudUniform.vs
- src/Interface/Modules/Render/ES/shaders/TextBuilder.vs
- src/Interface/Modules/Render/ES/systems/RenderTransText.cc
- src/Modules/Visualization/ShowColorMapModule.cc
Fixes color maps not rendering after draw order fix and fixes UI elements clipping with objects.
> Color Map Fix

- src/Dataflow/Serialization/Network/Importer/NetworkIO.cc
- src/Dataflow/Serialization/Network/Importer/NetworkIO.h
> Windows fix

- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewSceneControlsDock.cc
- src/Modules/Visualization/ShowFieldGlyphsPortHandler.cc
- src/Modules/Visualization/ShowFieldGlyphsPortHandler.h
> Lunch bugs

- src/Interface/Modules/Render/ES/SRCamera.cc
- src/Interface/Modules/Render/ES/SRCamera.h
- src/Interface/Modules/Render/ES/SRInterface.cc
- src/Interface/Modules/Render/ES/SRInterface.h
- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewScene.h
- src/Interface/Modules/Render/ViewSceneControls.ui
- src/Interface/Modules/Render/ViewSceneControlsDock.cc
- src/LATEST_TAG.txt
Adds auto rotate controls and @jessdtate's favorite feature resolving issues #1705 and #717.
> Auto rotate

- .github/labeler.yml
- .github/workflows/label.yml
> Try out PR labeler

- src/Interface/Modules/Render/ViewSceneControls.ui
- src/Interface/Modules/Render/ViewSceneControlsDock.cc
- src/Interface/Modules/Render/ViewSceneControlsDock.h
> fixed light ui

- src/Core/Datatypes/ColorMap.cc
> ported color maps

- src/Core/Application/Preferences/Preferences.cc
- src/Core/Application/Preferences/Preferences.h
- src/Interface/Application/Preferences.ui
- src/Interface/Application/PreferencesWindow.cc
- src/Interface/Application/PreferencesWindow.h
- src/Interface/Application/PythonConsoleWidget.h
- src/Interface/Application/SCIRunMainWindowSlotsPrivate.cc
- src/Interface/Application/Settings.cc
- src/Interface/Modules/Render/ES/SRInterface.cc
- src/Interface/Modules/Render/ES/SRInterface.h
- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewScene.h
- src/Interface/Modules/Render/ViewSceneControls.ui
- src/Interface/Modules/Render/ViewSceneControlsDock.cc
Example of pre-refactoring settings code change.
> Move VS settings

- src/Interface/Modules/Render/ViewScene.cc
- src/Modules/DataIO/CMakeLists.txt
- src/Modules/DataIO/ReadFile.cc
- src/Modules/DataIO/ReadFile.h
- src/Modules/Legacy/Fields/InsertHexVolSheetAlongSurface.cc
- src/Modules/Visualization/ShowColorMapModule.cc
- src/Modules/Visualization/ShowString.cc
- src/Modules/Visualization/TextBuilder.cc
@jessdtate Here are BBox fixes for various places, including ShowString.
The ReadFile code is work in progress, but can be merged now, no effect.
> Quick merge!

- .gitignore
- docs/_config.yml
- docs/scripts/cibuild.sh
Fix html-proofer errors from documentation site
> Fix Html Tests

- src/Core/GeometryPrimitives/BBox.cc
- src/Core/GeometryPrimitives/BBoxBase.h
- src/Graphics/Widgets/Tests/BasicBoundingBoxWidgetTest.cc
- src/Interface/Modules/Render/ES/RendererCollaborators.h
- src/Interface/Modules/Render/ES/SRInterface.cc
- src/Interface/Modules/Render/ES/SRInterface.h
- src/Interface/Modules/Render/ES/WidgetHandling.cc
- src/Interface/Modules/Render/Tests/ObjectScalingTests.cc
- src/Interface/Modules/Render/ViewScene.cc
- src/Interface/Modules/Render/ViewScene.h
- src/Interface/Modules/Render/ViewSceneControls.ui
Basic clipping plane and unit test fixes
> Final Z fixes
